services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: booking_service_zahin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure:2


  redis:
    container_name: redis
    image: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS:-nestjs_starter_demo}
    ports:
      - '6379:6379'
    restart: on-failure:2

  backend:
    build:
      context: ./backend
    ports:
      - "5015:5015"
    environment:
      - TARGET_ENV=development
      - DATABASE_URL=postgresql://postgres:1234@postgres:5432/booking_service_zahin
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    restart: on-failure:3

volumes:
  pgdata:
  pgadmin-data:
